channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=24.2
- pip:
  - mlflow==2.15.1
  - cloudpickle==3.0.0
  - imbalanced-learn==0.12.3
  - numpy==1.26.4
  - psutil==5.9.0
  - scikit-learn==1.5.1
  - scipy==1.14.0
name: mlflow-env
